apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: food-recipe-bot
    component: backend
spec:
  selector:
    app: food-recipe-bot
    component: backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
