services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    env_file:
      - .env
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000

  frontend:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./logs:/app/logs
      - ./static:/app/static
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8000  # ← Add this line
    command: streamlit run frontend/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - backend