apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: food-recipe-bot
    component: frontend
spec:
  selector:
    app: food-recipe-bot
    component: frontend
  ports:
  - port: 8501
    targetPort: 8501
    protocol: TCP
  type: LoadBalancer
